 [workspace]
  members = ["proxy", "starb"]

 [patch.crates-io]
  # Create EventLoop outside of main thread
  eframe = { path = "eframe-0.21.3" }

 [profile.dev]
  panic = "abort"

 [profile.release]
  panic = "abort"
