condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
error_on_line_overflow = true
error_on_unformatted = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "One"
hex_literal_case = "Upper"
imports_granularity = "Item"
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
version = "Two"
