 [registries.crates-io]
  protocol = "sparse"

 [build]
  target = "x86_64-pc-windows-gnu"
  rustflags = [
    # BEGIN - Embark standard lints v6 for Rust 1.55+
    # Do not change or add/remove from here.
    "-Dunsafe_code",
    "-Wclippy::all",
    "-Wclippy::await_holding_lock",
    "-Wclippy::char_lit_as_u8",
    "-Wclippy::checked_conversions",
    "-Wclippy::dbg_macro",
    "-Wclippy::debug_assert_with_mut_call",
    "-Wclippy::doc_markdown",
    "-Wclippy::empty_enum",
    "-Wclippy::enum_glob_use",
    "-Wclippy::exit",
    "-Wclippy::expl_impl_clone_on_copy",
    "-Wclippy::explicit_deref_methods",
    "-Wclippy::explicit_into_iter_loop",
    "-Wclippy::fallible_impl_from",
    "-Wclippy::filter_map_next",
    "-Wclippy::flat_map_option",
    "-Wclippy::float_cmp_const",
    "-Wclippy::from_iter_instead_of_collect",
    "-Wclippy::if_let_mutex",
    "-Wclippy::implicit_clone",
    "-Wclippy::imprecise_flops",
    "-Wclippy::inefficient_to_string",
    "-Wclippy::invalid_upcast_comparisons",
    "-Wclippy::large_digit_groups",
    "-Wclippy::large_stack_arrays",
    "-Wclippy::large_types_passed_by_value",
    "-Wclippy::let_unit_value",
    "-Wclippy::linkedlist",
    "-Wclippy::lossy_float_literal",
    "-Wclippy::macro_use_imports",
    "-Wclippy::manual_ok_or",
    "-Wclippy::map_err_ignore",
    "-Wclippy::map_flatten",
    "-Wclippy::map_unwrap_or",
    "-Wclippy::match_on_vec_items",
    "-Wclippy::match_same_arms",
    "-Wclippy::match_wild_err_arm",
    "-Wclippy::match_wildcard_for_single_variants",
    "-Wclippy::mem_forget",
    "-Wclippy::mismatched_target_os",
    "-Wclippy::missing_enforced_import_renames",
    "-Wclippy::mut_mut",
    "-Wclippy::mutex_integer",
    "-Wclippy::needless_borrow",
    "-Wclippy::needless_continue",
    "-Wclippy::needless_for_each",
    "-Wclippy::option_option",
    "-Wclippy::path_buf_push_overwrite",
    "-Wclippy::ptr_as_ptr",
    "-Wclippy::rc_mutex",
    "-Wclippy::ref_option_ref",
    "-Wclippy::rest_pat_in_fully_bound_structs",
    "-Wclippy::same_functions_in_if_condition",
    "-Wclippy::semicolon_if_nothing_returned",
    "-Wclippy::single_match_else",
    "-Wclippy::string_add_assign",
    "-Wclippy::string_add",
    "-Wclippy::string_lit_as_bytes",
    "-Wclippy::string_to_string",
    "-Wclippy::todo",
    "-Wclippy::trait_duplication_in_bounds",
    "-Wclippy::unimplemented",
    "-Wclippy::unnested_or_patterns",
    "-Wclippy::unused_self",
    "-Wclippy::useless_transmute",
    "-Wclippy::verbose_file_reads",
    "-Wclippy::zero_sized_map_values",
    "-Wfuture_incompatible",
    "-Wnonstandard_style",
    "-Wrust_2018_idioms",
    # END - Embark standard lints v6 for Rust 1.55+

    # Starb-specific overrides/additions:
    # This is a lot...
    "-Dclippy::default_union_representation",
    '-Dclippy::no_mangle_with_rust_abi',
    "-Dmissing_abi",
    "-Dunsafe_op_in_unsafe_fn",
    "-Wclippy::allow_attributes",
    "-Wclippy::allow_attributes_without_reason",
    "-Wclippy::as_ptr_cast_mut",
    "-Wclippy::as_underscore",
    "-Wclippy::bool_to_int_with_if",
    "-Wclippy::borrow_as_ptr",
    "-Wclippy::branches_sharing_code",
    "-Wclippy::case_sensitive_file_extension_comparisons",
    "-Wclippy::cast_lossless",
    "-Wclippy::clear_with_drain",
    "-Wclippy::clone_on_ref_ptr",
    "-Wclippy::cloned_instead_of_copied",
    "-Wclippy::collection_is_never_read",
    "-Wclippy::default_numeric_fallback",
    "-Wclippy::default_trait_access",
    "-Wclippy::deref_by_slicing",
    "-Wclippy::derive_partial_eq_without_eq",
    "-Wclippy::doc_link_with_quotes",
    "-Wclippy::empty_structs_with_brackets",
    "-Wclippy::equatable_if_let",
    "-Wclippy::format_push_string",
    "-Wclippy::future_not_send",
    "-Wclippy::implicit_hasher",
    "-Wclippy::inconsistent_struct_constructor",
    "-Wclippy::index_refutable_slice",
    "-Wclippy::inline_asm_x86_att_syntax",
    "-Wclippy::iter_not_returning_iterator",
    "-Wclippy::iter_on_empty_collections",
    "-Wclippy::iter_on_single_items",
    "-Wclippy::iter_with_drain",
    "-Wclippy::large_futures",
    "-Wclippy::let_underscore_untyped",
    "-Wclippy::manual_assert",
    "-Wclippy::manual_clamp",
    "-Wclippy::manual_instant_elapsed",
    "-Wclippy::manual_let_else",
    "-Wclippy::manual_ok_or",
    "-Wclippy::manual_string_new",
    "-Wclippy::many_single_char_names",
    "-Wclippy::mismatching_type_param_order",
    "-Wclippy::missing_assert_message",
    "-Wclippy::missing_const_for_fn",
    "-Wclippy::multiple_inherent_impl",
    "-Wclippy::must_use_candidate",
    "-Wclippy::mutex_atomic",
    "-Wclippy::naive_bytecount",
    "-Wclippy::needless_bitwise_bool",
    "-Wclippy::negative_feature_names",
    "-Wclippy::needless_collect",
    "-Wclippy::needless_pass_by_value",
    "-Wclippy::no_effect_underscore_binding",
    "-Wclippy::non_send_fields_in_send_ty",
    "-Wclippy::nonstandard_macro_braces",
    "-Wclippy::or_fun_call",
    "-Wclippy::pattern_type_mismatch",
    "-Wclippy::print_stderr",
    "-Wclippy::print_stdout",
    "-Wclippy::range_minus_one",
    "-Wclippy::range_plus_one",
    "-Wclippy::rc_buffer",
    "-Wclippy::redundant_closure_for_method_calls",
    "-Wclippy::redundant_else",
    "-Wclippy::redundant_feature_names",
    "-Wclippy::redundant_pub_crate",
    "-Wclippy::return_self_not_must_use",
    "-Wclippy::ref_binding_to_reference",
    "-Wclippy::separated_literal_suffix",
    "-Wclippy::single_char_lifetime_names",
    "-Wclippy::stable_sort_primitive",
    "-Wclippy::str_to_string",
    "-Wclippy::suboptimal_flops",
    "-Wclippy::tests_outside_test_module",
    "-Wclippy::trailing_empty_array",
    "-Wclippy::transmute_ptr_to_ptr",
    "-Wclippy::transmute_undefined_repr",
    "-Wclippy::trivial_regex",
    "-Wclippy::trivially_copy_pass_by_ref",
    "-Wclippy::type_repetition_in_bounds",
    "-Wclippy::try_err",
    "-Wclippy::unchecked_duration_subtraction",
    "-Wclippy::uninlined_format_args",
    "-Wclippy::unnecessary_box_returns",
    "-Wclippy::unnecessary_join",
    "-Wclippy::unnecessary_struct_initialization",
    "-Wclippy::unnecessary_wraps",
    "-Wclippy::unused_async",
    "-Wclippy::unused_peekable",
    "-Wclippy::unused_rounding",
    "-Wclippy::unneeded_field_pattern",
    "-Wclippy::unwrap_used",
    "-Wclippy::use_self",
    "-Wclippy::used_underscore_binding",
    "-Wclippy::useless_let_if_seq",
    "-Wclippy::verbose_bit_mask",
    "-Wclippy::wildcard_dependencies",
    "-Wclippy::wildcard_imports",
    "-Wclippy::string_add_assign",
    "-Aclippy::string_add",
    "-Aclippy::string_lit_as_bytes",
    "-Aclippy::useless_conversion",
    "-Aunsafe_code",

    # Only uncomment these temporarily!!
    # "-Wclippy::missing_docs_in_private_items",
    # "-Wclippy::multiple_unsafe_ops_per_block",
    # "-Wclippy::nursery",
    # "-Wclippy::pedantic",
    # "-Wclippy::significant_drop_tightening",
    # "-Wmissing_docs",
  ]
