[package]
name = "starb"
version = "3.1.0"
edition = "2021"

[dependencies]
egui = { version = "0.20.1", features = ["extra_debug_asserts"] }
eframe = "0.20.1"
starb-app = { path = "../starb-app" }
starb-config = { path = "../starb-config" }
starb-logging = { path = "../starb-logging" }
tracing = "0.1.37"
