[package]
name = "starb-config"
version = "0.0.0"
edition = "2021"

[dependencies]
once_cell = "1.17.0"
parking_lot = "0.12.1"
ron = "0.8.0"
serde = { version = "1.0.152", features = ["derive"] }
tracing = "0.1.37"
